[package]
name = "smolbar"
version = "0.3.2"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
description = "smol status command for sway"
license = "GPL-3.0-or-later"

[dependencies]
clap = { version = "3", features = ["derive"] }
dirs = "4"
libc = "0"
log = { version = "0", features = ["std"] }
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = { version = "1", features = ["time", "signal", "sync", "rt", "macros"] }
toml = { version = "0", features = ["preserve_order"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
