[package]
name = "smolbar"
version = "0.6.0"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
rust-version = "1.66.0"
description = "smol status command for sway"
homepage = "https://crates.io/crates/smolbar"
repository = "https://github.com/ulahello/smolbar"
license = "GPL-3.0-or-later"
keywords = ["sway", "swaybar"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4.0.29", features = ["derive"] }
dirs = "4.0.0"
libc = "0.2.138"
serde = "1.0.150"
serde_derive = "1.0.150"
serde_json = "1.0.89"
tokio = { version = "1.23.0", features = ["time", "signal", "sync", "rt", "macros"] }
toml = { version = "0.5.10", features = ["preserve_order"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[profile.release]
lto = true
codegen-units = 1
strip = true
