[package]
name = "smolbar"
version = "0.1.0"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
description = "smol status bar for sway"
license = "GPL-3.0-or-later"

[dependencies]
crossbeam-channel = "0.5"
rgb = "0.8"
serde = "1.0"
serde_derive = "1.0"
signal-hook = "0.3"
toml = { version = "0.5", features = ["preserve_order"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
