[package]
name = "smolbar"
version = "0.1.0"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
description = "smol status bar for sway"
license = "GPL-3.0-or-later"

[dependencies]
rgb = "0.8"
signal-hook = "0.3"

[profile.release]
lto = true
codegen-units = 1
strip = true
