[package]
name = "smolbar"
version = "0.1.0"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
description = "smol status command for sway"
license = "GPL-3.0-or-later"

[dependencies]
dirs = "4.0"
libc = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1.18", features = ["time", "signal", "sync", "rt", "macros"] }
toml = { version = "0.5", features = ["preserve_order"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
