[package]
name = "smolbar"
version = "0.8.0"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
rust-version = "1.66.1"
description = "smol status command for sway"
homepage = "https://crates.io/crates/smolbar"
repository = "https://github.com/ulahello/smolbar"
license = "GPL-3.0-or-later"
keywords = ["sway", "swaybar"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.71"
argh = "0.1.10"
dirs = "5.0.1"
libc = "0.2.143"
semver = { version = "1.0.17", default-features = false, features = ["serde"] }
serde = "1.0.162"
serde_derive = "1.0.162"
serde_json = "1.0.96"
signal-hook-registry = "1.4.1"
termcolor = "1.2.0"
tokio = { version = "1.28.0", default-features = false, features = ["time", "signal", "process", "sync", "rt", "macros"] }
tokio-util = { version = "0.7.8", default-features = false }
toml = { version = "0.7.3", default-features = false, features = ["parse", "preserve_order"] }
tracing = { version = "0.1.37", default-features = false, features = ["attributes"] }
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["ansi"] }

[profile.release]
lto = true
codegen-units = 1
strip = true
