[package]
name = "smolbar"
version = "0.7.3"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
rust-version = "1.66.1"
description = "smol status command for sway"
homepage = "https://crates.io/crates/smolbar"
repository = "https://github.com/ulahello/smolbar"
license = "GPL-3.0-or-later"
keywords = ["sway", "swaybar"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.70"
argh = "0.1.10"
dirs = "5.0.0"
libc = "0.2.140"
serde = "1.0.159"
serde_derive = "1.0.159"
serde_json = "1.0.95"
termcolor = "1.2.0"
tokio = { version = "1.27.0", features = ["time", "signal", "sync", "rt", "macros"] }
toml = { version = "0.7.3", default-features = false, features = ["parse", "preserve_order"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[profile.release]
lto = true
codegen-units = 1
strip = true
