[package]
name = "smolbar"
version = "0.5.2"
authors = ["Ula Shipman <ula.hello@mailbox.org>"]
edition = "2021"
description = "smol status command for sway"
homepage = "https://crates.io/crates/smolbar"
repository = "https://github.com/ulahello/smolbar"
license = "GPL-3.0-or-later"
keywords = ["sway", "swaybar"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "4"
libc = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = { version = "1", features = ["time", "signal", "sync", "rt", "macros"] }
toml = { version = "0", features = ["preserve_order"] }
tracing = "0"
tracing-subscriber = "0"

[profile.release]
lto = true
codegen-units = 1
strip = true
