command_dir = "blocks"

[memory]
command = "./memory_mem.sh"
prefix = "Mem "
interval = 5
color = "#8db6b2"
separator = false

[swap]
command = "./memory_swap.sh"
prefix = "Swap "
interval = 5
color = "#859e74"

[load_average]
command = "./load_average.sh"
interval = 10
color = "#e1605a"

[date]
command = "./date.sh"
interval = 1
color = "#f7bc5d"
