smolbar_version = "^0.8"
command_dir = "blocks"
separator_block_width = 16

[header]
stop_signal = "SIGINT"

[[block]]
command = "./memory_mem.sh"
prefix = "Mem "
interval = 5
color = "#7fbbb3"
separator = false

[[block]]
command = "./memory_swap.sh"
prefix = "Swap "
interval = 5
color = "#83c092"

[[block]]
command = "./load_average.sh"
interval = 10
color = "#e67e80"

[[block]]
command = "./date.sh"
interval = 1
color = "#ddbc7f"
