command_dir = "blocks"

[[block]]
command = "./memory_mem.sh"
prefix = "Mem "
interval = 5
color = "#8db6b2"
separator = false

[[block]]
command = "./memory_swap.sh"
prefix = "Swap "
interval = 5
color = "#859e74"

[[block]]
command = "./load_average.sh"
interval = 10
color = "#e1605a"

[[block]]
command = "./date.sh"
interval = 1
color = "#f7bc5d"
